### PR TITLE
GNOME Circle Tweaks

### LINKED ISSUE #268: GNOME Circle Tweaks
Source: https://gitlab.gnome.org/Teams/Circle/-/issues/128#note_1755755

- [x] Filename -> File Name
- [x]  Is there a way to remove downloads? I couldn't find one, at least. Would be nice to have some kind of menu on the rows for that, or selection mode.
    - Awaiting clarification
- [x] This menu looks like a save button, but it's something totally different. Given that there's not much in there I think these actions could all just go into the primary menu
    - Awaiting clarification  
    - image
- [x] I'd use a different icon for the logs thing here, e.g. maybe utilities-terminal?
    -  image
- [x] The welcome screen looks pretty good now, but the icon needs the icon-dropshadow class, and the labels could be more inviting. How about "Download Videos -- Add a video URL to start downloading"
- [x] Feature idea: If there's a recognized URL in the clipboard, show a toast allowing people to add it directly, like Fragments does

### PR DESCRIPTION
**Pull request by nlogozzo**
Closes #268

### CODE REVIEW

**Comment by nlogozzo** [comment]
@fsobolev @DaPigGuy Clipboard updates for you to check:
- Clipboard validation now only checks if the URL scheme is valid instead of actually running it through yt-dlp (yt-dlp validate will occur from the AddDownloadDialog when the user clicks the Validate button like always)
- I can't seem to reproduce your guys issue with not seeing validation on startup. The way I test it is, I copy a like from YouTube and then right away open Tube Converter and it detects it no problem
- Either way if it doesn't work on startup, when the `Add Download` button is clicked, the AddDownloadDialog will check the clipboard again and paste the link into the `Media URL` row if valid:
image

Let me know how it works for you guys :)

**Comment by fsobolev** [comment]
> I can't seem to reproduce your guys issue with not seeing validation on startup. The way I test it is, I copy a like from YouTube and then right away open Tube Converter and it detects it no problem

I guess again like with callbacks its affected by PC speed. For me it needs about a second after a window opens for gdk to get the data from clipboard. If you want to make this feature realible, you could try connecting to `changed` event, and the first time it triggers validate clipboard and then disconnect event.

> when the Add Download button is clicked, the AddDownloadDialog will check the clipboard again and paste the link into the Media URL row if valid:

There's probably nothing we really can do but I dislike how the toast overlaps the button 😞

**Comment by nlogozzo** [comment]
> If you want to make this feature realible, you could try connecting to changed event, and the first time it triggers validate clipboard and then disconnect event.

Ok I'll look it to that. In the mean time if you open AddDownloadDialog it should detect it there and then paste it for you to validate to accommodate that.

> There's probably nothing we really can do but I dislike how the toast overlaps the button 😞

I mean probably not, it's called ToastOverlay so I guess it's expected. We could add a margin to the bottom of the Validate button which will leave room for the overlay. I mean we did get yelled at that in circle review but maybe this time it will be justified 😆

**Comment by nlogozzo** [comment]
> Is there a way to remove downloads? I couldn't find one, at least. Would be nice to have some kind of menu on the rows for that, or selection mode. 
> This menu looks like a save button, but it's something totally different. Given that there's not much in there I think these actions could all just go into the primary menu 

image

Added the option to clear all completed downloads and moved the actions from the `Downloader` menu into buttons in the group headers. I think i'll add text to the buttons too...

**Comment by nlogozzo** [comment]
image

That's better

**Comment by nlogozzo** [comment]
OK, PR ready :)

**Comment by DaPigGuy** [comment]
Having both an icon and label for the buttons seem like an odd choice, especially for the Completed group, where only the `Clear` button has a label. Maybe remove the label?

**Comment by nlogozzo** [comment]
> Having both an icon and label for the buttons seem like an odd choice, especially for the Completed group, where only the Clear button has a label. Maybe remove the label?

I feel like that's pretty common. Here's Settings:
image

As far as only the `Clear` label in `Completed` group, it's the same like in `HeaderBar`s where usually the first button (the most common action) has a label and the others are only icons. Here's Tagger:
image

**Comment by DaPigGuy** [comment]
Fair enough, but definitely deal with the toast getting in the way of the Validate button :sweat_smile:

**Comment by nlogozzo** [comment]
> Fair enough, but definitely deal with the toast getting in the way of the Validate button sweat_smile

Yeah I'm going to try something ...

**Comment by nlogozzo** [comment]
@DaPigGuy Ok try it now., the dialog will grow and shrink for when the toast is shown and dismissed respectively.
The toast will also automatically dismiss once the validate button is pressed (or enter on the url entry).

**Comment by DaPigGuy** [comment]
Seems okay to me

**Pull request merged**
