### PR TITLE
Tube Converter --> Parabolic

### LINKED ISSUE #351: New Name
https://gitlab.gnome.org/Teams/Circle/-/issues/128#note_1766039

Suggestions:
- <del>Receiver</del> existing GNOME project
- Catcher (Would require new icon)

### PR DESCRIPTION
**Pull request by nlogozzo**
Closes #351

### CODE REVIEW

**Comment by nlogozzo** [comment]
@soumyaDghosh Is there anything we need to update in `snapcraft.yml` and on the snap website for this change?

**Comment by nlogozzo** [comment]
Also if @fsobolev or someone wants to update `banner-snap.png`. I just made it the same as the regular `banner.png` since I'm not on Ubuntu. So it's just has a `blue` accent color instead of `orange`.

**Comment by soumyaDghosh** [comment]
I would like to halt this change for some time and ask for suggestions from the snapcraft admin, I hope, next publish isn't soon

**Comment by nlogozzo** [comment]
> I would like to halt this change for some time and ask for suggestions from the snapcraft admin, I hope, next publish isn't soon

Ok, I'd like to get it merged into `main` today/tomorrow to give translators time to update translations before a release on Friday...

**Comment by nlogozzo** [comment]
The repo name will stay `TubeConverter` and code files will stay `TubeConverter` if that helps...just the string shown in the app will change from `TubeConverter` to `Parabolic`.

**Comment by nlogozzo** [comment]
image
So i can probably just change the `Title` and `Images` and be ok...

**Comment by nlogozzo** [comment]
Ok, ready for merge :)

**Pull request merged**
